### ISSUE TITLE
New fields on exciting tables is now shown in BREAD editor

### ISSUE THREAD

**Issue by Drivez** [thedevdojo/voyager#1223]
- Laravel Version: 5.4
- Voyager Version: 0.11.10
- PHP Version: 7.1
- Database Driver & Version: Mysql

### Description:
New fields added to the database after bread was created should appear in the bread editor.
Currently adding new fields to a table is not shown in the bread editor.

### Steps To Reproduce:
install with dummy data, try adding a new field on an exciting table, the new field is not shown in the bread editor

**Comment by abdgad** [comment]
After you add new fields to a table, you will need to `Edit BREAD` for that table and hit save for the changes to take effect.

**Comment by fletch3555** [comment]
@abdgad, he was saying that they're not appearing in the BREAD editor at all.  Would the `save` action create those entries?

**Comment by johnteee** [comment]
@abdgad In my case, after new fields are added, the new columns' indexes would not appear.
Same as @Drivez , I think it's a bug after order field added in 0.11.10.

The error message:

![image](https://cloud.githubusercontent.com/assets/527058/25847936/c4b1f590-34ea-11e7-91e6-d6881ecd6d9d.png)

**Comment by johnteee** [comment]
Finally there's a workaround:
Delete the previous BREAD record first and set it again.
However it would cause risks to make wrong settings when we setup new BREAD informations.

In my point of view, new added columns such as added by migrations or by Voyager Admin, they should be checked if they didn't have any record in the BREAD.
Now the columns in BREAD editing pages seem to be generated according the BREAD records, however some of them might not be in the records.

**Comment by johnteee** [comment]
https://github.com/the-control-group/voyager/commit/5461692d0e51571c3e6df059e6e2eff461910e95

It seems to be fixed(not in 0.11.10 anyway :P)
It might be fixed in version 0.11.11

Currently I modified the codes of Voyager manually for workaround.

**Comment by abdgad** [comment]
Sorry for the misunderstanding.
@marktopper @fletch3555 we should tag a release.

**Comment by markoliverbrawn** [comment]
Any fix for this yet?

**Comment by nunomsh** [comment]
I'm facing the same problem, any field added after creating the BREAD does not show. If you try to order the existing fields, it wont work, because it's missing the field in data_rows
I've notice that the order in the data_rows is always set to "1". Shouldn't this order be incremented? When the bread is created, it should give the order=order+1 to each field. Or at least give the order = index of the foreach that inserts the content in the data_rows table...

The solution is to manually add the new field created in the table data_rows. this way the bread and order works fine
I using 0.11.10. This problem does not happen in version 0.11.9

**Comment by nunomsh** [comment]
The "fix" is to delete the bread, and create it again... Not a fix, but at least you wont loose any data

**Comment by markoliverbrawn** [comment]
Are there any immediate plans to (really) fix this?

**Comment by fletch3555** [comment]
Did anyone confirm this was/wasn't fixed in 0.11.11?

If not, you should be able to just open and save the bread without making any changes (after adding the fields obviously).  I agree it's still an issue that would need to be fixed though.

**Comment by markoliverbrawn** [comment]
Has 0.11.11 been released yet?

**Comment by fletch3555** [comment]
Apologies, I thought it had.  Please test with the master branch. You can change composer to use "dev-master" as the version

**Comment by markoliverbrawn** [comment]
Looks good. Thanks.

**Comment by fletch3555** [comment]
Closing this as it's been confirmed fixed in master.  If it hasn't made it to a release yet (unlikely), it will soon.

**Comment by ghost** [comment]
@fletch3555 still the same problem in laravel 5.5.1 voyager dev-master
