### ISSUE TITLE
php artisan migrate:refresh returns error on fresh install

### ISSUE THREAD

**Issue by adddz** [thedevdojo/voyager#1766]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:

After a fresh install of Laravel and Voyager, if I try to run `php artisan migrate:refresh` it returns error.

```
php artisan migrate:refresh --seed


  [Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
```

**Comment by mortenscheel** [comment]
I ran into the same issue, but I managed to fix it by modifying a hack someone else made in [this comment](https://github.com/laravel/framework/issues/1186#issuecomment-118194746).

Adding this to my AppServiceProvider's boot method fixed it for me.

`Schema::getConnection()->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'blob');`

**Comment by fletch3555** [comment]
@marktopper, is this worth adding to the ServiceProvider in https://github.com/larapack/doctrine-support? Not sure if you already have something there or if it needs modifying

**Comment by marktopper** [comment]
I will get this added to the Doctrine Support service provider.

**Comment by marktopper** [comment]
This have been fixed in `larapack/doctrine-support:v0.1.4`.
https://github.com/larapack/doctrine-support/commit/02c9fc73324d9111bb03bb8b087653afde8972e0

Please run `composer update larapack/doctrine-support`

**Comment by BeetleJ** [comment]
Any word on this issue. Seems to still not be working correctly. Still getting "This type is not supported".

**Comment by fletch3555** [comment]
Not sure what word you're looking for.  The issue was closed 22 days ago with a comment of "please run composer update ...."

**Comment by BeetleJ** [comment]
I did the composer update larapack/doctrine-support but still get the error "generic.exception: Enum type is not supported", and I am unable to add any new columns to a table that uses ENUM.
