### ISSUE TITLE
Backslashes in media asset path when saving to db

### ISSUE THREAD

**Issue by eddielee394** [thedevdojo/voyager#2834]
- Laravel Version: 5.6.12
- Voyager Version: dev-1.x-dev
- PHP Version: 7.1
- Database Driver & Version:
10.1.19 MariaDB

### Description:
Encountering an issue where media asset paths being saved to database are using back slashes `\` instead of forward slashes `/`

```
//view
<div style="background-image:url('{{  Voyager::image($page_data->image); }}');"></div>

//browser output
<div style="background-image:url('http://voyager.lar/storage/pages\March2018\j5hUZQly1g9m7x7YM2uT.jpg'); "></div>
```
Double checked my storage & file system config & all seems to set correctly, as the image paths are being rendered, just with the weird slash issue.  I was able to fix the paths using `str_replace` with my controller, but am trying to understand if this is a voyager error or if there's another underlying issue unique to my environment causing this behavior.  

- When uploading an image via admin, relative path is being saved in the db using forward slashes `pages\March2018\L2GNsd5rkrxFMb4G7Rcx.jpg`
- Image media paths renders correctly with forward slashes when image is viewed within voyager media panel.  

Environment:  
Win7 xampp with vhost aliasing enabled.  

### Steps To Reproduce:
- Upload image file to media library 
- Output image within a view using the `Voyager::image()` helper

###Possible Causes
- Changes made in 1.x-dev branch from slashes to `DIRECTORY_SEPARATOR`

**Comment by emptynick** [comment]
Fixed in #2837

**Comment by felipe-machado** [comment]
I am getting this in v1.1.3 but it was working fine before the update

**Comment by pakalbekim** [comment]
I'm also still having this issue in the current newest version. Every time I upload an image (creating a new record) I get backslashes. using Windows 10.

**Comment by emptynick** [comment]
When using `Voyager::image(...)` this shouldn't be a problem:
https://github.com/the-control-group/voyager/blob/410a54820a90c881e4a08f7ea49c5f113ee8fdda/src/Voyager.php#L228-L235

**Comment by pakalbekim** [comment]
Thanks for the tip!
