### ISSUE TITLE
Problem with voyager avatar and folder path.

### ISSUE THREAD

**Issue by sgxtract** [thedevdojo/voyager#3811]
## Version information
 - Laravel: v5.7.17
 - Voyager: v1.1
 - PHP: 7.2.12
 - Database: MySQL

## Description
The image for the avatar is broken, and the path for the default.png is not working.

## Screenshots
![image](https://user-images.githubusercontent.com/25955772/50048671-7aebff00-010d-11e9-8a3c-7f282b8d797d.png)

## Additional context
Also I would like to ask if the Voyager 1.1 has different path for the /storage?

**Comment by gcolotti** [comment]
Run the command "php artisan storage:link". [Here](https://laravel.com/docs/5.7/filesystem) you have more info.

**Comment by sgxtract** [comment]
> Run the command "php artisan storage:link". [Here](https://laravel.com/docs/5.7/filesystem) you have more info.

I already tried it, and I also tried deleting the file and running it again. 
![image](https://user-images.githubusercontent.com/25955772/50048718-999ec580-010e-11e9-9de7-e291a329b552.png)

**Comment by gcolotti** [comment]
Try with `php artisan config:cache`. If still fails, check #722, this [link](https://stackoverflow.com/questions/39496598/laravel-5-3-storagelink-symlink-protocol-error) and this [comment](https://github.com/the-control-group/voyager/issues/1397#issuecomment-386267875).

**Comment by emptynick** [comment]
Make sure the file actually exists.
If not, you face the problem mentioned in https://github.com/the-control-group/voyager/issues/3354
@TheyCallMeSurf clearing the config cache is not related in any way.

**Comment by gcolotti** [comment]
@emptynick some ppl said clearing cache solved this issue after creating the symlink to storage

**Comment by fletch3555** [comment]
Clearing config cache would only work if you changed the setup in config/filesystems.php and had the config cached before.

Please make sure `public/storage` is actually a symlink to `storage/app/public`, and not just a directory.  I see you're in windows, but if you had a bash terminal (cygwin, git-bash, etc), you could run `la -al public/` to see what it shows as.  Or view properties in windows explorer. Should show as a "junction" or something I think

**Comment by KonradMil** [comment]
Make sure you have a correct APP_URL in .env

**Comment by lfranz** [comment]
The issue is caused by an incorrect APP_URL. Try to change that value

**Comment by emptynick** [comment]
His menu makes me think he isn't using dummy-data, so he's facing the issue mentioned in #3354 which was fixed in https://github.com/the-control-group/voyager/pull/3818.
Please run `php artisan vendor:publish --tag=voyager_avatar`
Closing for now.
If this didn't help, please let us know and we'll reopen this one.

**Comment by anis096-dev** [comment]
I tried and it called default.png but in admin panel, still broken !!!
