### ISSUE TITLE
Issue with Voyager Font Awesome icons not displaying properly [BUG]

### ISSUE THREAD

**Issue by smhboc** [thedevdojo/voyager#4130]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.3 
 - PHP: 7.3

## Description
I have a problem with displaying icons.
And I have another problem and its about alerts the main page like Users count and Pages count and Posts count.

 <img width="1321" alt="background" src="https://user-images.githubusercontent.com/30196953/57501547-36037780-72fd-11e9-9524-4ffed5dca32b.png">
 My Panel!

<img width="1055" alt="background_main" src="https://user-images.githubusercontent.com/30196953/57501871-6e578580-72fe-11e9-80c1-f94920f40c53.png">
I want informations tabs like this.

## Screenshots

<img width="253" alt="icon1" src="https://user-images.githubusercontent.com/30196953/57501548-369c0e00-72fd-11e9-841d-30bfcd084d13.png">
<img width="827" alt="icon2" src="https://user-images.githubusercontent.com/30196953/57501549-369c0e00-72fd-11e9-9041-9e1eec5c680e.png">
<img width="1187" alt="icon3" src="https://user-images.githubusercontent.com/30196953/57501550-3734a480-72fd-11e9-9c3b-6294c90ae751.png">

**Comment by orodrigue12** [comment]
Change your vendor\tcg\voyager directory to a new directory from and properly voyager project.

**Comment by fletch3555** [comment]
You need to provide more information.... Any errors in the logs? browser console?

**Comment by Uzi99** [comment]
Sorry for interrupt but I'm facing with same issue, the functionality is properly working while the fonts are not showing.. the console error is below,
![error](https://user-images.githubusercontent.com/46163275/58326151-668ef980-7e45-11e9-9bbd-91e281a93adb.png)

**Comment by likedo** [comment]
I confirm it too. The fonts are not loaded correctly.

<img width="1692" alt="Schermata 2019-06-06 alle 11 21 55" src="https://user-images.githubusercontent.com/8256514/59022044-5582b700-884d-11e9-9d13-b0f884bae709.png">

**Comment by FlickTheManual** [comment]
![image](https://user-images.githubusercontent.com/2384206/59023123-23c71b80-8860-11e9-8c15-99c22e444b5b.png)

![image](https://user-images.githubusercontent.com/2384206/59023166-36d9eb80-8860-11e9-8ab6-2ee37dd13599.png)

maybe here...

edit: the css file is `resources/app.css` from `vendor/tcg/voyager` folder

**Comment by Leon-d-j** [comment]
+1 
![image](https://user-images.githubusercontent.com/44633190/59028002-c2507e00-885a-11e9-85ae-86f8d0a01aab.png)

**Comment by kurianbenny** [comment]
I have also faced the same issue
![voyegar](https://user-images.githubusercontent.com/11265654/59027738-75c76b80-8877-11e9-9041-fd613238ac5a.jpeg)

**Comment by magyar** [comment]
I have similar problems, but on the latest version after installation
Laravel: v5.8
Voyager: v1.2.5
PHP: 7.3

**Comment by kurianbenny** [comment]
> I have similar problems, but on the latest version after installation
> Laravel: v5.8
> Voyager: v1.2.5
> PHP: 7.3

Same here

**Comment by likedo** [comment]
> I have similar problems, but on the latest version after installation
Laravel: v5.8
Voyager: v1.2.5
PHP: 7.3

Same!

**Comment by ArroWsGM** [comment]
@all
Guys just forgot to change fonts path in `vendor/tcg/voyager/resources/assets/sass/fonts.css`
temporary solution:
copy `vendor/tcg/voyager/resources/assets/sass/fonts.css`
to
`public/css`
open it and change font path from
`assets?path=fonts/voyager...`
to
`/admin/voyager-assets?path=fonts/voyager...`

and include it in the voyager config
```
...
    'additional_css' => [
       'css/fonts.css',
    ],
...
```

**Comment by emptynick** [comment]
Update to 1.2.6 and clear your browser-cache

@ArroWsGM that cant work. This file wont be included from Voyager.

**Comment by likedo** [comment]
@emptynick 
Fantastic!
Thanks now works by upgrading to version 1.2.6

**Comment by Leon-d-j** [comment]
@emptynick  Good job, Thankyou!

**Comment by ArroWsGM** [comment]
@emptynick
Obviously, it needs to be included in voyager config:
```
...
    'additional_css' => [
       'css/fonts.css',
    ],
...
```
I'm forgot to mention about it, sorry

**Comment by Hermit503** [comment]
No bug with version 1.2.6

**Comment by kurianbenny** [comment]
> Update to 1.2.6 and clear your browser-cache
> 
> @ArroWsGM that cant work. This file wont be included from Voyager.

Its working now with 1.2.6

**Comment by fletch3555** [comment]
Resolved, closing

**Comment by OtiZ2** [comment]
I use "tcg/voyager": "^1.3"
but still have this bug

![image](https://user-images.githubusercontent.com/11439000/69014249-90565280-0988-11ea-8cb9-f5b68da9e8eb.png)

![image](https://user-images.githubusercontent.com/11439000/69014255-a401b900-0988-11ea-8584-89edd2c581e4.png)

**Comment by kanokith** [comment]
I got this bug on  version 1.3 too.

**Comment by kanokith** [comment]
@OtiZ2 I just solved this by enable php extension file_info

**Comment by OtiZ2** [comment]
> @OtiZ2 I just solved this by enable php extension file_info

hi, i got extension file_info enabled.
But still not worked

**Comment by abdelkadergelany** [comment]
> @ALL
> Guys just forgot to change fonts path in `vendor/tcg/voyager/resources/assets/sass/fonts.css`
> temporary solution:
> copy `vendor/tcg/voyager/resources/assets/sass/fonts.css`
> to
> `public/css`
> open it and change font path from
> `assets?path=fonts/voyager...`
> to
> `/admin/voyager-assets?path=fonts/voyager...`
> 
> and include it in the voyager config
> 
> ```
> ...
>     'additional_css' => [
>        'css/fonts.css',
>     ],
> ...
> ```

please can you give more details? which public folder ? the one in my main App?

**Comment by ArroWsGM** [comment]
> > @ALL
> > Guys just forgot to change fonts path in `vendor/tcg/voyager/resources/assets/sass/fonts.css`
> > temporary solution:
> > copy `vendor/tcg/voyager/resources/assets/sass/fonts.css`
> > to
> > `public/css`
> > open it and change font path from
> > `assets?path=fonts/voyager...`
> > to
> > `/admin/voyager-assets?path=fonts/voyager...`
> > and include it in the voyager config
> > ```
> > ...
> >     'additional_css' => [
> >        'css/fonts.css',
> >     ],
> > ...
> > ```
> 
> please can you give more details? which public folder ? the one in my main App?

In the laravel root, I don't know other public folder in laravel)) But, I think this bug is already fixed.

**Comment by OtiZ2** [comment]
My problem is solve with
php artisan config:cache 
:D

**Comment by faisalahamed** [comment]
I just solved this by enable php extension file_info

**Comment by reiisrei** [comment]
I enabled php extension file_info but still not working. Still no fix for this?

**Comment by Payetus** [comment]
> I enabled php extension file_info but still not working. Still no fix for this?

I still have this problem

**Comment by ahmedbakri2020** [comment]
I solved this by enable php extension file_info

**Comment by dzung1nguyen** [comment]
I am using v1.4 and docker. It is working at local, but when i deploy to server, can not load fonts and images (js and css can load). 
Laravel 8.x
Voyager:  1.4

I just debug in VoyagerController:
- I put content to a file, it is okay. 
- But when i return as a response, an error display: The image “http://abc.local/admin/voyager-assets?path=images%2Flogo-icon-light.png” cannot be displayed because it contains errors. (Firefox and request return a status code 200).

No errors in log file.
