### ISSUE TITLE
Can't update permissions when edit role

### ISSUE THREAD

**Issue by d3turnes** [thedevdojo/voyager#4668]
## Version information

 - Laravel: v5.7.*
 - Voyager: v1.3.0 || v1.3.1
 - PHP: 7.1.30
 - Database: MySQL 8.0

## Description

Can't update permissions when edit role, duplicate route
PUT|PATCH voyager.roles.update TCG\Voyager\Http\Controllers\VoyagerBaseController@update
PUT|PATCH voyager.roles.update TCG\Voyager\Http\Controllers\VoyagerRoleController@update

## Steps To Reproduce
1. Edit role
2. Select permissions (p.e posts)
3. Send
4. Instead of executing  VoyagerRoleController@update, VoyagerBaseController@update is executed

## A possible solution
1. Edit Bread Role and add VoyagerRoleController as Main Controller

**Comment by MrCrayon** [comment]
Can you list exact versions installed not what you are requiring? 
Voyager can be 1.3.0 or 1.3.1

Is this happening on a new install or it started after an update?

**Comment by d3turnes** [comment]
this happening on a new install
checked in both versions ( v1.3.0 and v1.3.1 )

**Comment by fadymondy** [comment]
i have the same problem in 1.3.1

**Comment by MrCrayon** [comment]
I was able to reproduce the bug, not really sure yet when this started.

Quick fix without changing any code set in `roles` BREAD configuration as Controller
`TCG\Voyager\Http\Controllers\VoyagerRoleController`

![Schermata da 2020-01-02 02-56-54](https://user-images.githubusercontent.com/6875243/71649025-98393e80-2d0b-11ea-87ae-8ae38e525b5a.png)

**Comment by MrCrayon** [comment]
@d3turnes v1.3.0 works fine.

The problem is the double declaration of the routes but the second one overrode the first one until #4605 (merged in 1.3.1) where parameter was changed causing two routes to coesist:
```
PUT|PATCH | admin/roles/{id}
PUT|PATCH | admin/roles/{role}
```

**Comment by MrCrayon** [comment]
Fixed with #4669

**Comment by admont28** [comment]
> I was able to reproduce the bug, not really sure yet when this started.
> 
> Quick fix without changing any code set in `roles` BREAD configuration as Controller
> `TCG\Voyager\Http\Controllers\VoyagerRoleController`
> 
> ![Schermata da 2020-01-02 02-56-54](https://user-images.githubusercontent.com/6875243/71649025-98393e80-2d0b-11ea-87ae-8ae38e525b5a.png)

Same error in v1.3.1

I fixed it by editing the **"Controller Name"** of roles by _**"TCG \ Voyager \ Http \ Controllers \ VoyagerRoleController"**_

![image](https://user-images.githubusercontent.com/6698179/72665762-71e8f380-39d9-11ea-9a53-a61935944130.png)

**Comment by panjitito** [comment]
Thank you, it works for me.
![image](https://user-images.githubusercontent.com/44996401/73335544-4ea82900-42a2-11ea-9d76-b2f80bf0115c.png)

**Comment by bcmarcos03** [comment]
> _**TCG \ Voyager \ Http \ Controllers \ VoyagerRoleController"**_

Thank you! This worked for me!

**Comment by kingIZZZY** [comment]
Voyager: v1.3.1
Issue still persists
This is NOT fixed yet, i.e. default vanilla installation of voyager still results in erroneous saving of users/roles

**Comment by MrCrayon** [comment]
@kingIZZZY This bug affects only v.1.3.1, it's fixed in 1.3-dev and next release (v1.3.2) will contain fix.
You can fix it in the way described in my other comment.

**Comment by kingIZZZY** [comment]
How can I `composer update` to the bleeding edge latest commits?
Even as time goes on and more commits happen it would be great if i can keep updating to the latest fixes

**Comment by hirbod** [comment]
NOT fixed for me in 1.4-dev. I can't update the Roles page. Adding 
TCG\Voyager\Http\Controllers\VoyagerRoleController als Controller name for BREAD "roles", and calling "php artisan optimize" worked for me.

**Comment by emptynick** [comment]
That's what's in the upgrade guide for 1.4, yes.

**Comment by MrCrayon** [comment]
@Hirbod that's because the final fix is setting that in BREAD but if you are updating you need to do that manually.
There was a temporary fix in 1.3.2 that didn't require to set that because it's a breaking change.
