### ISSUE TITLE
Duplicate key name error when updating a table with unique columns

### ISSUE THREAD

**Issue by Frondor** [thedevdojo/voyager#478]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.5
- PHP Version: 7
- Database Driver & Version: MySQL 5.7.11

### Description:
If I create a table with an `unique` column, I can't update it from voyager anymore because it doesn't check if the key is already there, and it turns into a 
```
QueryException in Connection.php line 770:
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'services_name_unique' (SQL: alter table `services` add unique `services_name_unique`(`name`))
```

### Steps To Reproduce:
![https://i.gyazo.com/342572c068ea4997115f1656930194a0.gif](https://i.gyazo.com/342572c068ea4997115f1656930194a0.gif)

**Comment by fletch3555** [comment]
I'm not sure if this was fixed yet, but please update voyager to latest(currently v0.10.7) and test again.

**Comment by Frondor** [comment]
I can confirm it still happens on .10.7
Create a new table with an unique column and then try to update it (no changes needed).

**Comment by Frondor** [comment]
@marktopper can you pay a look here? Just updated my installation and it is still happening.

**Comment by handiwijoyo** [comment]
This issue has been fixed on #518

**Comment by kevinjon27** [comment]
@handiwijoyo I can confirm it still happen too on 0.10.10. Update user table for add new field. Thank you

**Comment by marktopper** [comment]
The pull request from @handiwijoyo have not been merged yet since it have some issues.
Im open for other pull requests to fix this.

**Comment by Frondor** [comment]
This error is still here @ v10.12
Even if I try and delete the `unique` row, more errors pop up. The row is updated but with errors (can't remember right now).

To reproduce: install v10.12 (latest) -> go to `pages` table -> update it.
See the error? Now try to delete the `unique` table

**Comment by zietbukuel** [comment]
Same here, I create a table with a unique field, then without doing any changes I hit update and I get this:
`
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'products_slug_unique' (SQL: alter table `products` add unique `products_slug_unique`(`slug`))`

**Comment by grandsilence** [comment]
bug still present( I'll try to fix this later with pull request

**Comment by Skyrant** [comment]
I still have this error when i install WHMCS, what is the status or is there a workaround?

**Comment by handiwijoyo** [comment]
This is an issue with older Voyager version. Please open a new issue if you still have this error.
