### ISSUE TITLE
No Fields when Adding new Entry after first Creation of BREAD

### ISSUE THREAD

**Issue by thedevdojo** [thedevdojo/voyager#514]
- Laravel Version: 5.3
- Voyager Version: 0.10.8
- PHP Version: 7
- Database Driver & Version: Mysql

### Description:

When you go to create a new BREAD type from a database table and you go to add a new entry for that BREAD, it does not show the fields you specified in the BREAD creation. You have to go back to the BREAD and edit it and submit it again. (checkout the video)

### Steps To Reproduce:

Quick video screencast of this issue (1 min. 25 seconds)
https://www.youtube.com/watch?v=nmZBVAyNvnI

**Comment by RandyBooth** [comment]
This is my first time install this package and came to find out it not showing fields! That is also apply to table that is already exist and not showing fields on first create 'bread'! 

@thedevdojo Thank you for showing me to edit again to fix this!

**Comment by karandatwani92** [comment]
yes it's happening but even after editing it and submitting it again i got an exception on create.

Undefined variable: dataTypeContent (View: C:\wamp\www\taxi\vendor\tcg\voyager\resources\views\bread\edit-add.blade.php)

**Comment by akazorg** [comment]
+1

**Comment by marktopper** [comment]
This should have been fixed in the latest release.

Else please ping me to reopen.

**Comment by EngHazem** [comment]
@marktopper 

I'm facing this error now, I believe it is not fixed yet.
