### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name >> When saving changes in "/admin/database/categories/edit" form

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#515]
- Laravel Version: 5.3
- Voyager Version: 0.10.8
- PHP Version: 5.6

Getting this error:

`ueryException in Connection.php line 770:
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'categories_slug_unique' (SQL: alter table `categories` add unique `categories_slug_unique`(`slug`))`

**Comment by vanloc0301** [comment]
Check in your database at table `categories`.

Seem you have more than 1 at fields `categories_slug_unique`.

Primary key or Unique should be the only one.

Try to change values that. Hope can help you.

**Comment by hazem1taha** [comment]
@vanloc0301 
Thanks, but this didn't help.

**Comment by handiwijoyo** [comment]
You may have duplicate slug name in your categories table.

**Comment by handiwijoyo** [comment]
I think this issue is related with #478 and have been fixed on #518

**Comment by hazem1taha** [comment]
@handiwijoyo 

Is this merged to the latest release? as the problem still exists and not solved.

**Comment by handiwijoyo** [comment]
Sorry, I just found new problem on my PR #518. It's related with enum type. Will continue working on it.

**Comment by Frondor** [comment]
That's why you should write tests before! :laughing:

**Comment by handiwijoyo** [comment]
This issue has been fixed on `1.0`
