### ISSUE TITLE
Category always return to the first category

### ISSUE THREAD

**Issue by ergxpr0xy** [thedevdojo/voyager#835]
- Laravel Version: 5.4.13
- Voyager Version: 0.11.3
- PHP Version: 
- Database Driver & Version:

### Description:
Category always return to the first category (category_id 1)
![2017-02-27 3](https://cloud.githubusercontent.com/assets/19571567/23362351/f8ffebf4-fd27-11e6-8c5b-e9be0162e174.png)
![2017-02-27 1](https://cloud.githubusercontent.com/assets/19571567/23362352/f902fd30-fd27-11e6-8d08-079da4c31676.png)
![2017-02-27 2](https://cloud.githubusercontent.com/assets/19571567/23362353/f904408c-fd27-11e6-8c23-43cd94a80c3c.png)

**Comment by dimsanchuk** [comment]
![image](https://cloud.githubusercontent.com/assets/13986110/23436282/9ee647d0-fe12-11e6-9664-cf810412099b.png)
Field "category_id" must be "Select Dropdown".

**Comment by ergxpr0xy** [comment]
turns out the default input type for it was checkbox, i hope it gets fixed in the next update. thank you!

**Comment by waelwalid** [comment]
1 - Edit bread of post
2 - convert it to Dropdown menu

It works with me

**Comment by marktopper** [comment]
Correct @waelwalid.
However I have left this open since it's still not the default value in the seeders.

I'm open for pull requests optimizing this.

**Comment by fletch3555** [comment]
I'm closing this since it's 4.5 months old now.  We can revisit these issues once 1.0 gets released.
